/**/controller_manager:
  ros__parameters:
    update_rate: 250
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

    gpio_command_controller:
      type: gpio_controllers/GpioCommandController

/**/gpio_command_controller:
  ros__parameters:
    gpios:
      - gpio_io
    command_interfaces:
      gpio_io:
        interfaces:
          - digital_output_1
          - digital_output_2
          - digital_output_3
          - digital_output_4
          - digital_output_5
          - digital_output_6
          - digital_output_7
          - digital_output_8
          - digital_output_9
          - digital_output_10
          - digital_output_11
          - digital_output_12
          - digital_output_13
          - digital_output_14
          - digital_output_15
          - digital_output_16
    state_interfaces:
      gpio_io:
        interfaces:
          - digital_input_1
          - digital_input_2
          - digital_input_3
          - digital_input_4
          - digital_input_5
          - digital_input_6
          - digital_input_7
          - digital_input_8
          - digital_input_9
          - digital_input_10
          - digital_input_11
          - digital_input_12
          - digital_input_13
          - digital_input_14
          - digital_input_15
          - digital_input_16
          - digital_output_1
          - digital_output_2
          - digital_output_3
          - digital_output_4
          - digital_output_5
          - digital_output_6
          - digital_output_7
          - digital_output_8
          - digital_output_9
          - digital_output_10
          - digital_output_11
          - digital_output_12
          - digital_output_13
          - digital_output_14
          - digital_output_15
          - digital_output_16

/**/joint_trajectory_controller:
  ros__parameters:
    joints:
      - $(var tf_prefix)joint_1
      - $(var tf_prefix)joint_2
      - $(var tf_prefix)joint_3
      - $(var tf_prefix)joint_4
      - $(var tf_prefix)joint_5
      - $(var tf_prefix)joint_6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    constraints:
      decelerate_on_cancel: true
      $(var tf_prefix)joint_1:
        max_deceleration_on_cancel: 0.5
      $(var tf_prefix)joint_2:
        max_deceleration_on_cancel: 0.5
      $(var tf_prefix)joint_3:
        max_deceleration_on_cancel: 0.5
      $(var tf_prefix)joint_4:
        max_deceleration_on_cancel: 0.5
      $(var tf_prefix)joint_5:
        max_deceleration_on_cancel: 0.5
      $(var tf_prefix)joint_6:
        max_deceleration_on_cancel: 0.5

/**/force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: $(var tf_prefix)ft_sensor
    frame_id: $(var tf_prefix)ft_frame
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    sensor_filter_chain:
      filter1:
        name: fts_lowpass_filter
        type: control_filters/LowPassFilterWrench 
        params:
          sampling_frequency: 500.0 
          damping_frequency: 5.0 
          damping_intensity: 0.0
